In [1]:
## Q1. Install and load the latest versions of TensorFlow and Keras. Print their versions.

# Install TensorFlow and Keras
!pip install tensorflow keras

# Load the libraries
import tensorflow as tf
from tensorflow import keras

# Print their versions
print("TensorFlow version:", tf.__version__)
print("Keras version:", keras.__version__)


TensorFlow version: 2.17.0
Keras version: 3.5.0


In [9]:
import tensorflow as tf
from tensorflow import keras

# Print the versions
print(f"TensorFlow version: {tf.__version__}")
print(f"Keras version: {keras.__version__}")


TensorFlow version: 2.17.0
Keras version: 3.5.0


In [7]:
# If you haven't installed TensorFlow yet, uncomment the following line:
# !pip install tensorflow

import tensorflow as tf
from tensorflow import keras

# Print the versions
print(f"TensorFlow version: {tf.__version__}")
print(f"Keras version: {keras.__version__}")


TensorFlow version: 2.17.0
Keras version: 3.5.0


In [11]:
## Q3. Check for null values, identify categorical variables, and encode them.

import pandas as pd
import seaborn as sns
# Load the dataset
df = sns.load_dataset('titanic')  # Replace 'titanic.csv' with your dataset file


In [13]:
# Check for null values
null_values = df.isnull().sum()
print("Null Values in Each Column:\n", null_values)


Null Values in Each Column:
 survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [15]:
# Identify categorical variables
categorical_vars = df.select_dtypes(include=['object', 'category']).columns
print("\nCategorical Variables:\n", categorical_vars)



Categorical Variables:
 Index(['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive'], dtype='object')


In [17]:
# One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=categorical_vars, drop_first=True)
print("\nData after One-Hot Encoding:\n", df_encoded.head())



Data after One-Hot Encoding:
    survived  pclass   age  sibsp  parch     fare  adult_male  alone  sex_male  \
0         0       3  22.0      1      0   7.2500        True  False      True   
1         1       1  38.0      1      0  71.2833       False  False     False   
2         1       3  26.0      0      0   7.9250       False   True     False   
3         1       1  35.0      1      0  53.1000       False  False     False   
4         0       3  35.0      0      0   8.0500        True   True      True   

   embarked_Q  ...  who_woman  deck_B  deck_C  deck_D  deck_E  deck_F  deck_G  \
0       False  ...      False   False   False   False   False   False   False   
1       False  ...       True   False    True   False   False   False   False   
2       False  ...       True   False   False   False   False   False   False   
3       False  ...       True   False    True   False   False   False   False   
4       False  ...      False   False   False   False   False   False   False

In [19]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Example: encoding 'Embarked' variable if it's ordinal
if 'Embarked' in categorical_vars:
    df['Embarked'] = label_encoder.fit_transform(df['Embarked'])
    print("\nData after Label Encoding for 'Embarked':\n", df[['Embarked']].head())


In [23]:
## Q4. Separate the features and target variables from the dataset.


import pandas as pd

# Sample dataset
data = {
    'feature1': [1, 2, 3],
    'feature2': [4, 5, 6],
    'target': [0, 1, 0]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Separate features and target
X = df[['feature1', 'feature2']]  # Features
y = df['target']                   # Target

print("Features:\n", X)
print("Target:\n", y)


Features:
    feature1  feature2
0         1         4
1         2         5
2         3         6
Target:
 0    0
1    1
2    0
Name: target, dtype: int64


In [25]:
import numpy as np

# Sample dataset
data = np.array([[1, 4, 0],
                 [2, 5, 1],
                 [3, 6, 0]])

# Separate features and target
X = data[:, :-1]  # All rows, all columns except the last
y = data[:, -1]   # All rows, only the last column

print("Features:\n", X)
print("Target:\n", y)


Features:
 [[1 4]
 [2 5]
 [3 6]]
Target:
 [0 1 0]


In [27]:
from sklearn.model_selection import train_test_split
import pandas as pd

# Sample dataset
data = {
    'feature1': [1, 2, 3],
    'feature2': [4, 5, 6],
    'target': [0, 1, 0]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Separate features and target
X = df[['feature1', 'feature2']]
y = df['target']

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Features:\n", X_train)
print("Testing Features:\n", X_test)
print("Training Target:\n", y_train)
print("Testing Target:\n", y_test)


Training Features:
    feature1  feature2
1         2         5
2         3         6
Testing Features:
    feature1  feature2
0         1         4
Training Target:
 1    1
2    0
Name: target, dtype: int64
Testing Target:
 0    0
Name: target, dtype: int64


In [29]:
## Q5. Perform a train-test split, dividing the data into training, validation, and test datasets.



import pandas as pd
from sklearn.model_selection import train_test_split

# Sample data
data = pd.DataFrame({
    'feature1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'target': [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
})

# First, split into training and temp (validation + test)
train_data, temp_data = train_test_split(data, test_size=0.4, random_state=42)

# Now, split temp into validation and test
val_data, test_data = train_test_split(temp_data, test_size=0.5, random_state=42)

print("Training Data:\n", train_data)
print("Validation Data:\n", val_data)
print("Test Data:\n", test_data)


Training Data:
    feature1  target
7         8       1
2         3       0
9        10       1
4         5       0
3         4       1
6         7       0
Validation Data:
    feature1  target
8         9       0
5         6       1
Test Data:
    feature1  target
1         2       1
0         1       0


In [31]:
import numpy as np

# Sample data
data = np.array([[1, 0], [2, 1], [3, 0], [4, 1], [5, 0], 
                 [6, 1], [7, 0], [8, 1], [9, 0], [10, 1]])

# Shuffle the data
np.random.seed(42)
np.random.shuffle(data)

# Calculate split indices
train_size = int(0.6 * len(data))
val_size = int(0.2 * len(data))

# Split the data
train_data = data[:train_size]
val_data = data[train_size:train_size + val_size]
test_data = data[train_size + val_size:]

print("Training Data:\n", train_data)
print("Validation Data:\n", val_data)
print("Test Data:\n", test_data)


Training Data:
 [[9 0]
 [2 1]
 [6 1]
 [1 0]
 [8 1]
 [3 0]]
Validation Data:
 [[10  1]
 [ 5  0]]
Test Data:
 [[4 1]
 [7 0]]


In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Sample imbalanced data
data = pd.DataFrame({
    'feature1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'target': [0, 0, 0, 1, 1, 1, 0, 1, 0, 1]
})

# First, split into training and temp (validation + test) with stratification
train_data, temp_data = train_test_split(data, test_size=0.4, stratify=data['target'], random_state=42)

# Now, split temp into validation and test
val_data, test_data = train_test_split(temp_data, test_size=0.5, stratify=temp_data['target'], random_state=42)

print("Training Data:\n", train_data)
print("Validation Data:\n", val_data)
print("Test Data:\n", test_data)


Training Data:
    feature1  target
7         8       1
8         9       0
1         2       0
4         5       1
5         6       1
2         3       0
Validation Data:
    feature1  target
3         4       1
6         7       0
Test Data:
    feature1  target
9        10       1
0         1       0


In [35]:
### Q6. Scale the dataset using an appropriate scaling technique.

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Sample dataset
data = {'Feature1': [10, 20, 30, 40, 50],
        'Feature2': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(df)

# Convert back to DataFrame
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
print(scaled_df)


   Feature1  Feature2
0      0.00      0.00
1      0.25      0.25
2      0.50      0.50
3      0.75      0.75
4      1.00      1.00


In [37]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Sample dataset
data = {'Feature1': [10, 20, 30, 40, 50],
        'Feature2': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(df)

# Convert back to DataFrame
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
print(scaled_df)


   Feature1  Feature2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214


In [39]:
import pandas as pd
from sklearn.preprocessing import RobustScaler

# Sample dataset with outliers
data = {'Feature1': [10, 20, 30, 40, 1000],
        'Feature2': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)

# Initialize the RobustScaler
scaler = RobustScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(df)

# Convert back to DataFrame
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
print(scaled_df)


   Feature1  Feature2
0      -1.0      -1.0
1      -0.5      -0.5
2       0.0       0.0
3       0.5       0.5
4      48.5       1.0


In [41]:
### Q7. Design and implement at least two hidden layers and an output layer for the binary categoricalvariables.

import numpy as np
from keras.models import Sequential
from keras.layers import Dense

# Generate dummy data
X = np.random.rand(1000, 20)  # 1000 samples, 20 features
y = np.random.randint(2, size=(1000, 1))  # Binary target variable

# Create the model
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=20))  # First hidden layer
model.add(Dense(32, activation='relu'))  # Second hidden layer
model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Fit the model
model.fit(X, y, epochs=10, batch_size=32)


C:\Users\PC\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5296 - loss: 0.6972
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5409 - loss: 0.6912
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5469 - loss: 0.6901
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5494 - loss: 0.6859
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5519 - loss: 0.6867
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5674 - loss: 0.6841
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5660 - loss: 0.6794 
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5778 - loss: 0.6805 
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5287 - loss: 0.6833 
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5877 - loss: 0.6754


In [43]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# Input data
X = np.random.rand(1000, 20)  # 1000 samples, 20 features
y = np.random.randint(2, size=(1000, 1))  # Binary target variable

# Initialize weights
input_layer_neurons = 20
hidden_layer1_neurons = 64
hidden_layer2_neurons = 32
output_neurons = 1

weights_input_hidden1 = np.random.rand(input_layer_neurons, hidden_layer1_neurons)
weights_hidden1_hidden2 = np.random.rand(hidden_layer1_neurons, hidden_layer2_neurons)
weights_hidden2_output = np.random.rand(hidden_layer2_neurons, output_neurons)

# Training the model
for epoch in range(10000):
    # Forward propagation
    hidden_layer1_output = sigmoid(np.dot(X, weights_input_hidden1))
    hidden_layer2_output = sigmoid(np.dot(hidden_layer1_output, weights_hidden1_hidden2))
    output = sigmoid(np.dot(hidden_layer2_output, weights_hidden2_output))

    # Backpropagation
    output_error = y - output
    output_delta = output_error * sigmoid_derivative(output)

    hidden_layer2_error = output_delta.dot(weights_hidden2_output.T)
    hidden_layer2_delta = hidden_layer2_error * sigmoid_derivative(hidden_layer2_output)

    hidden_layer1_error = hidden_layer2_delta.dot(weights_hidden1_hidden2.T)
    hidden_layer1_delta = hidden_layer1_error * sigmoid_derivative(hidden_layer1_output)

    # Update weights
    weights_hidden2_output += hidden_layer2_output.T.dot(output_delta)
    weights_hidden1_hidden2 += hidden_layer1_output.T.dot(hidden_layer2_delta)
    weights_input_hidden1 += X.T.dot(hidden_layer1_delta)


In [45]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define the neural network architecture
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.hidden1 = nn.Linear(20, 64)  # First hidden layer
        self.hidden2 = nn.Linear(64, 32)   # Second hidden layer
        self.output = nn.Linear(32, 1)     # Output layer

    def forward(self, x):
        x = torch.relu(self.hidden1(x))  # Activation for first hidden layer
        x = torch.relu(self.hidden2(x))  # Activation for second hidden layer
        x = torch.sigmoid(self.output(x)) # Sigmoid for output layer
        return x

# Create the model
model = NeuralNetwork()

# Loss and optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Dummy data
X = torch.rand(1000, 20)  # 1000 samples, 20 features
y = torch.randint(0, 2, (1000, 1)).float()  # Binary target variable

# Training loop
for epoch in range(10):
    model.train()
    optimizer.zero_grad()
    outputs = model(X)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')


ModuleNotFoundError: No module named 'torch'

In [47]:
## Q8. Create a Sequential model in Keras and add the previously designed layers to it.

from keras.models import Sequential
from keras.layers import Dense, Activation

# Initialize the Sequential model
model = Sequential()

# Add layers to the model
model.add(Dense(64, input_dim=10))  # Input layer with 10 features
model.add(Activation('relu'))        # Activation layer
model.add(Dense(1))                  # Output layer

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')


C:\Users\PC\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [49]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

# Initialize the Sequential model
model = Sequential()

# Add layers to the model
model.add(Dense(128, input_dim=20, activation='relu'))  # First hidden layer
model.add(Dropout(0.5))                                  # Dropout layer to prevent overfitting
model.add(Dense(64, activation='relu'))                  # Second hidden layer
model.add(Dense(1, activation='sigmoid'))                # Output layer for binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


C:\Users\PC\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [51]:
from keras.models import Sequential
from keras.layers import Dense, BatchNormalization

# Initialize the Sequential model
model = Sequential()

# Add layers to the model
model.add(Dense(256, input_dim=30, activation='relu'))  # First hidden layer
model.add(BatchNormalization())                          # Batch normalization layer
model.add(Dense(128, activation='relu'))                # Second hidden layer
model.add(Dense(10, activation='softmax'))              # Output layer for multi-class classification

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


C:\Users\PC\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [53]:
###Q9. Print the summary of the model architecture.

from keras.models import Sequential
from keras.layers import Dense

# Create a simple model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(32,)))
model.add(Dense(10, activation='softmax'))

# Print the model summary
model.summary()


C:\Users\PC\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                     │ (None, 64)                  │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,762 (10.79 KB)

 Trainable params: 2,762 (10.79 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
!pip install torchsummary


In [57]:
import torch
import torch.nn as nn
from torchsummary import summary

# Define a simple model
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(32, 64)
        self.fc2 = nn.Linear(64, 10)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

# Create the model
model = SimpleModel()

# Print the model summary
summary(model, (32,))


ModuleNotFoundError: No module named 'torch'

In [61]:
## Q10. Set the loss function(‘binary_crossentropy’), optimizer, and include the accuracy metric in the model.


from keras.models import Sequential
from keras.layers import Dense

# Initialize the model
model = Sequential()

# Add layers to the model
model.add(Dense(10, activation='relu', input_shape=(input_dim,)))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

print("Model compiled successfully with binary_crossentropy loss and accuracy metric!")


NameError: name 'input_dim' is not defined